baseURL = 'https://started-hugo.netlify.app/'
languageCode = 'pt-BR'
title = 'Started Hugo Netlify'
languageName = "Português Brasileiro"

disableHugoGeneratorInject = true
enableRobotsTXT = true
preserveTaxonomyNames = true
Paginate = 3